const navigationConfig = [
  {
    id: "calendar",
    title: "Dashboard",
    type: "item",
    icon: "dashboard",
    url: "apps/dashboard",
    access: ["Lawyer"],
  },
  {
    id: "contacts",
    title: "Contacts",
    type: "item",
    icon: "account_box",
    url: "apps/contacts/all",
    access: ["Lawyer"],
  },
  {
    id: "dossiers",
    title: "Dossiers",
    type: "item",
    icon: "view_column",
    url: "apps/dossiers/all",
    access: ["Lawyer"],
  },
  // {
  //   id: 'Étapes',
  //   title: 'Étapes',
  //   translate: 'Étapes',
  //   type: 'item',
  //   icon: 'view_agenda',
  //   url: 'apps/etapes/all',
  // },
  // {
  //   id: "Email",
  //   title: "Email",
  //   translate: "Email",
  //   type: "item",
  //   icon: "email",
  //   url: "apps/email/all",
  // },
  // {
  //   id: 'Agenda',
  //   title: 'Agenda',
  //   translate: 'Agenda',
  //   type: 'item',
  //   icon: 'event',
  //   url: 'apps/natures/all',
  // },
  {
    id: "client_dashboard",
    title: "Dashboard",
    type: "item",
    icon: "dashboard",
    url: "apps/client_dashboard",
    access: ["Client"],
  },
  {
    id: "message",
    title: "Messages",
    type: "item",
    icon: "mail",
    url: "apps/chat",
    access: ["Client"],
  },
  {
    id: "faq",
    title: "Foire aux Questions",
    type: "item",
    icon: "help_outline",
    url: "apps/faq",
    access: ["Client"],
  },
  // {
  //   id: 'Applicab',
  //   title: 'Applicab',
  //   translate: 'Applicab',
  //   type: 'item',
  //   icon: 'Applicab',
  //   url: 'apps/applicab/all',
  // },
];
export default navigationConfig;
