const navigationConfig = [
  {
    id: "calendar",
    title: "Dashboard",
    translate: "Dashboard",
    type: "item",
    icon: "dashboard",
    url: "apps/dashboard",
  },
  {
    id: "contacts",
    title: "Contacts",
    translate: "CONTACTS",
    type: "item",
    icon: "account_box",
    url: "apps/contacts/all",
  },
  {
    id: "dossiers",
    title: "Dossiers",
    translate: "Dossiers",
    type: "item",
    icon: "view_column",
    url: "apps/dossiers/all",
  },
  // {
  //   id: 'Étapes',
  //   title: 'Étapes',
  //   translate: 'Étapes',
  //   type: 'item',
  //   icon: 'view_agenda',
  //   url: 'apps/etapes/all',
  // },
  // {
  //   id: "Email",
  //   title: "Email",
  //   translate: "Email",
  //   type: "item",
  //   icon: "email",
  //   url: "apps/email/all",
  // },
  // {
  //   id: 'Agenda',
  //   title: 'Agenda',
  //   translate: 'Agenda',
  //   type: 'item',
  //   icon: 'event',
  //   url: 'apps/natures/all',
  // },
  // {
  //   id: 'faq',
  //   title: 'Foire aux Questions',
  //   translate:'Foire aux Questions',
  //   type: 'item',
  //   icon: 'help_outline',
  //   url: 'pages/faq',
  // },
  // {
  //   id: 'Applicab',
  //   title: 'Applicab',
  //   translate: 'Applicab',
  //   type: 'item',
  //   icon: 'Applicab',
  //   url: 'apps/applicab/all',
  // },
];
export default navigationConfig;
