# Generated by Django 3.0 on 2022-02-07 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caseManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nature',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
