# Generated by Django 3.0 on 2022-02-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caseManagement', '0002_auto_20220207_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nature',
            old_name='user_id',
            new_name='user',
        ),
    ]
