# Generated by Django 3.0 on 2022-02-07 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caseManagement', '0003_auto_20220207_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nature',
            name='user',
        ),
        migrations.AddField(
            model_name='nature',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user_id'),
        ),
    ]
