# Generated by Django 3.0 on 2022-02-07 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caseManagement', '0005_auto_20220207_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nature',
            name='user_id',
        ),
    ]
