# Generated by Django 3.0 on 2022-02-07 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caseManagement', '0007_nature_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nature',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='re_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
