const Countries = [
    {
        num_code: "4",
        alpha_2_code: "AF",
        alpha_3_code: "AFG",
        label: "Afghanistan",
        nationality: "Afghan",
    },
    {
        num_code: "248",
        alpha_2_code: "AX",
        alpha_3_code: "ALA",
        label: "\u00c5land Islands",
        nationality: "\u00c5land Island",
    },
    {
        num_code: "8",
        alpha_2_code: "AL",
        alpha_3_code: "ALB",
        label: "Albania",
        nationality: "Albanian",
    },
    {
        num_code: "12",
        alpha_2_code: "DZ",
        alpha_3_code: "DZA",
        label: "Algeria",
        nationality: "Algerian",
    },
    {
        num_code: "16",
        alpha_2_code: "AS",
        alpha_3_code: "ASM",
        label: "American Samoa",
        nationality: "American Samoan",
    },
    {
        num_code: "20",
        alpha_2_code: "AD",
        alpha_3_code: "AND",
        label: "Andorra",
        nationality: "Andorran",
    },
    {
        num_code: "24",
        alpha_2_code: "AO",
        alpha_3_code: "AGO",
        label: "Angola",
        nationality: "Angolan",
    },
    {
        num_code: "660",
        alpha_2_code: "AI",
        alpha_3_code: "AIA",
        label: "Anguilla",
        nationality: "Anguillan",
    },
    {
        num_code: "10",
        alpha_2_code: "AQ",
        alpha_3_code: "ATA",
        label: "Antarctica",
        nationality: "Antarctic",
    },
    {
        num_code: "28",
        alpha_2_code: "AG",
        alpha_3_code: "ATG",
        label: "Antigua and Barbuda",
        nationality: "Antiguan or Barbudan",
    },
    {
        num_code: "32",
        alpha_2_code: "AR",
        alpha_3_code: "ARG",
        label: "Argentina",
        nationality: "Argentine",
    },
    {
        num_code: "51",
        alpha_2_code: "AM",
        alpha_3_code: "ARM",
        label: "Armenia",
        nationality: "Armenian",
    },
    {
        num_code: "533",
        alpha_2_code: "AW",
        alpha_3_code: "ABW",
        label: "Aruba",
        nationality: "Aruban",
    },
    {
        num_code: "36",
        alpha_2_code: "AU",
        alpha_3_code: "AUS",
        label: "Australia",
        nationality: "Australian",
    },
    {
        num_code: "40",
        alpha_2_code: "AT",
        alpha_3_code: "AUT",
        label: "Austria",
        nationality: "Austrian",
    },
    {
        num_code: "31",
        alpha_2_code: "AZ",
        alpha_3_code: "AZE",
        label: "Azerbaijan",
        nationality: "Azerbaijani, Azeri",
    },
    {
        num_code: "44",
        alpha_2_code: "BS",
        alpha_3_code: "BHS",
        label: "Bahamas",
        nationality: "Bahamian",
    },
    {
        num_code: "48",
        alpha_2_code: "BH",
        alpha_3_code: "BHR",
        label: "Bahrain",
        nationality: "Bahraini",
    },
    {
        num_code: "50",
        alpha_2_code: "BD",
        alpha_3_code: "BGD",
        label: "Bangladesh",
        nationality: "Bangladeshi",
    },
    {
        num_code: "52",
        alpha_2_code: "BB",
        alpha_3_code: "BRB",
        label: "Barbados",
        nationality: "Barbadian",
    },
    {
        num_code: "112",
        alpha_2_code: "BY",
        alpha_3_code: "BLR",
        label: "Belarus",
        nationality: "Belarusian",
    },
    {
        num_code: "56",
        alpha_2_code: "BE",
        alpha_3_code: "BEL",
        label: "Belgium",
        nationality: "Belgian",
    },
    {
        num_code: "84",
        alpha_2_code: "BZ",
        alpha_3_code: "BLZ",
        label: "Belize",
        nationality: "Belizean",
    },
    {
        num_code: "204",
        alpha_2_code: "BJ",
        alpha_3_code: "BEN",
        label: "Benin",
        nationality: "Beninese, Beninois",
    },
    {
        num_code: "60",
        alpha_2_code: "BM",
        alpha_3_code: "BMU",
        label: "Bermuda",
        nationality: "Bermudian, Bermudan",
    },
    {
        num_code: "64",
        alpha_2_code: "BT",
        alpha_3_code: "BTN",
        label: "Bhutan",
        nationality: "Bhutanese",
    },
    {
        num_code: "68",
        alpha_2_code: "BO",
        alpha_3_code: "BOL",
        label: "Bolivia (Plurinational State of)",
        nationality: "Bolivian",
    },
    {
        num_code: "535",
        alpha_2_code: "BQ",
        alpha_3_code: "BES",
        label: "Bonaire, Sint Eustatius and Saba",
        nationality: "Bonaire",
    },
    {
        num_code: "70",
        alpha_2_code: "BA",
        alpha_3_code: "BIH",
        label: "Bosnia and Herzegovina",
        nationality: "Bosnian or Herzegovinian",
    },
    {
        num_code: "72",
        alpha_2_code: "BW",
        alpha_3_code: "BWA",
        label: "Botswana",
        nationality: "Motswana, Botswanan",
    },
    {
        num_code: "74",
        alpha_2_code: "BV",
        alpha_3_code: "BVT",
        label: "Bouvet Island",
        nationality: "Bouvet Island",
    },
    {
        num_code: "76",
        alpha_2_code: "BR",
        alpha_3_code: "BRA",
        label: "Brazil",
        nationality: "Brazilian",
    },
    {
        num_code: "86",
        alpha_2_code: "IO",
        alpha_3_code: "IOT",
        label: "British Indian Ocean Territory",
        nationality: "BIOT",
    },
    {
        num_code: "96",
        alpha_2_code: "BN",
        alpha_3_code: "BRN",
        label: "Brunei Darussalam",
        nationality: "Bruneian",
    },
    {
        num_code: "100",
        alpha_2_code: "BG",
        alpha_3_code: "BGR",
        label: "Bulgaria",
        nationality: "Bulgarian",
    },
    {
        num_code: "854",
        alpha_2_code: "BF",
        alpha_3_code: "BFA",
        label: "Burkina Faso",
        nationality: "Burkinab\u00e9",
    },
    {
        num_code: "108",
        alpha_2_code: "BI",
        alpha_3_code: "BDI",
        label: "Burundi",
        nationality: "Burundian",
    },
    {
        num_code: "132",
        alpha_2_code: "CV",
        alpha_3_code: "CPV",
        label: "Cabo Verde",
        nationality: "Cabo Verdean",
    },
    {
        num_code: "116",
        alpha_2_code: "KH",
        alpha_3_code: "KHM",
        label: "Cambodia",
        nationality: "Cambodian",
    },
    {
        num_code: "120",
        alpha_2_code: "CM",
        alpha_3_code: "CMR",
        label: "Cameroon",
        nationality: "Cameroonian",
    },
    {
        num_code: "124",
        alpha_2_code: "CA",
        alpha_3_code: "CAN",
        label: "Canada",
        nationality: "Canadian",
    },
    {
        num_code: "136",
        alpha_2_code: "KY",
        alpha_3_code: "CYM",
        label: "Cayman Islands",
        nationality: "Caymanian",
    },
    {
        num_code: "140",
        alpha_2_code: "CF",
        alpha_3_code: "CAF",
        label: "Central African Republic",
        nationality: "Central African",
    },
    {
        num_code: "148",
        alpha_2_code: "TD",
        alpha_3_code: "TCD",
        label: "Chad",
        nationality: "Chadian",
    },
    {
        num_code: "152",
        alpha_2_code: "CL",
        alpha_3_code: "CHL",
        label: "Chile",
        nationality: "Chilean",
    },
    {
        num_code: "156",
        alpha_2_code: "CN",
        alpha_3_code: "CHN",
        label: "China",
        nationality: "Chinese",
    },
    {
        num_code: "162",
        alpha_2_code: "CX",
        alpha_3_code: "CXR",
        label: "Christmas Island",
        nationality: "Christmas Island",
    },
    {
        num_code: "166",
        alpha_2_code: "CC",
        alpha_3_code: "CCK",
        label: "Cocos (Keeling) Islands",
        nationality: "Cocos Island",
    },
    {
        num_code: "170",
        alpha_2_code: "CO",
        alpha_3_code: "COL",
        label: "Colombia",
        nationality: "Colombian",
    },
    {
        num_code: "174",
        alpha_2_code: "KM",
        alpha_3_code: "COM",
        label: "Comoros",
        nationality: "Comoran, Comorian",
    },
    {
        num_code: "178",
        alpha_2_code: "CG",
        alpha_3_code: "COG",
        label: "Congo (Republic of the)",
        nationality: "Congolese",
    },
    {
        num_code: "180",
        alpha_2_code: "CD",
        alpha_3_code: "COD",
        label: "Congo (Democratic Republic of the)",
        nationality: "Congolese",
    },
    {
        num_code: "184",
        alpha_2_code: "CK",
        alpha_3_code: "COK",
        label: "Cook Islands",
        nationality: "Cook Island",
    },
    {
        num_code: "188",
        alpha_2_code: "CR",
        alpha_3_code: "CRI",
        label: "Costa Rica",
        nationality: "Costa Rican",
    },
    {
        num_code: "384",
        alpha_2_code: "CI",
        alpha_3_code: "CIV",
        label: "C\u00f4te d'Ivoire",
        nationality: "Ivorian",
    },
    {
        num_code: "191",
        alpha_2_code: "HR",
        alpha_3_code: "HRV",
        label: "Croatia",
        nationality: "Croatian",
    },
    {
        num_code: "192",
        alpha_2_code: "CU",
        alpha_3_code: "CUB",
        label: "Cuba",
        nationality: "Cuban",
    },
    {
        num_code: "531",
        alpha_2_code: "CW",
        alpha_3_code: "CUW",
        label: "Cura\u00e7ao",
        nationality: "Cura\u00e7aoan",
    },
    {
        num_code: "196",
        alpha_2_code: "CY",
        alpha_3_code: "CYP",
        label: "Cyprus",
        nationality: "Cypriot",
    },
    {
        num_code: "203",
        alpha_2_code: "CZ",
        alpha_3_code: "CZE",
        label: "Czech Republic",
        nationality: "Czech",
    },
    {
        num_code: "208",
        alpha_2_code: "DK",
        alpha_3_code: "DNK",
        label: "Denmark",
        nationality: "Danish",
    },
    {
        num_code: "262",
        alpha_2_code: "DJ",
        alpha_3_code: "DJI",
        label: "Djibouti",
        nationality: "Djiboutian",
    },
    {
        num_code: "212",
        alpha_2_code: "DM",
        alpha_3_code: "DMA",
        label: "Dominica",
        nationality: "Dominican",
    },
    {
        num_code: "214",
        alpha_2_code: "DO",
        alpha_3_code: "DOM",
        label: "Dominican Republic",
        nationality: "Dominican",
    },
    {
        num_code: "218",
        alpha_2_code: "EC",
        alpha_3_code: "ECU",
        label: "Ecuador",
        nationality: "Ecuadorian",
    },
    {
        num_code: "818",
        alpha_2_code: "EG",
        alpha_3_code: "EGY",
        label: "Egypt",
        nationality: "Egyptian",
    },
    {
        num_code: "222",
        alpha_2_code: "SV",
        alpha_3_code: "SLV",
        label: "El Salvador",
        nationality: "Salvadoran",
    },
    {
        num_code: "226",
        alpha_2_code: "GQ",
        alpha_3_code: "GNQ",
        label: "Equatorial Guinea",
        nationality: "Equatorial Guinean, Equatoguinean",
    },
    {
        num_code: "232",
        alpha_2_code: "ER",
        alpha_3_code: "ERI",
        label: "Eritrea",
        nationality: "Eritrean",
    },
    {
        num_code: "233",
        alpha_2_code: "EE",
        alpha_3_code: "EST",
        label: "Estonia",
        nationality: "Estonian",
    },
    {
        num_code: "231",
        alpha_2_code: "ET",
        alpha_3_code: "ETH",
        label: "Ethiopia",
        nationality: "Ethiopian",
    },
    {
        num_code: "238",
        alpha_2_code: "FK",
        alpha_3_code: "FLK",
        label: "Falkland Islands (Malvinas)",
        nationality: "Falkland Island",
    },
    {
        num_code: "234",
        alpha_2_code: "FO",
        alpha_3_code: "FRO",
        label: "Faroe Islands",
        nationality: "Faroese",
    },
    {
        num_code: "242",
        alpha_2_code: "FJ",
        alpha_3_code: "FJI",
        label: "Fiji",
        nationality: "Fijian",
    },
    {
        num_code: "246",
        alpha_2_code: "FI",
        alpha_3_code: "FIN",
        label: "Finland",
        nationality: "Finnish",
    },
    {
        num_code: "250",
        alpha_2_code: "FR",
        alpha_3_code: "FRA",
        label: "France",
        nationality: "French",
    },
    {
        num_code: "254",
        alpha_2_code: "GF",
        alpha_3_code: "GUF",
        label: "French Guiana",
        nationality: "French Guianese",
    },
    {
        num_code: "258",
        alpha_2_code: "PF",
        alpha_3_code: "PYF",
        label: "French Polynesia",
        nationality: "French Polynesian",
    },
    {
        num_code: "260",
        alpha_2_code: "TF",
        alpha_3_code: "ATF",
        label: "French Southern Territories",
        nationality: "French Southern Territories",
    },
    {
        num_code: "266",
        alpha_2_code: "GA",
        alpha_3_code: "GAB",
        label: "Gabon",
        nationality: "Gabonese",
    },
    {
        num_code: "270",
        alpha_2_code: "GM",
        alpha_3_code: "GMB",
        label: "Gambia",
        nationality: "Gambian",
    },
    {
        num_code: "268",
        alpha_2_code: "GE",
        alpha_3_code: "GEO",
        label: "Georgia",
        nationality: "Georgian",
    },
    {
        num_code: "276",
        alpha_2_code: "DE",
        alpha_3_code: "DEU",
        label: "Germany",
        nationality: "German",
    },
    {
        num_code: "288",
        alpha_2_code: "GH",
        alpha_3_code: "GHA",
        label: "Ghana",
        nationality: "Ghanaian",
    },
    {
        num_code: "292",
        alpha_2_code: "GI",
        alpha_3_code: "GIB",
        label: "Gibraltar",
        nationality: "Gibraltar",
    },
    {
        num_code: "300",
        alpha_2_code: "GR",
        alpha_3_code: "GRC",
        label: "Greece",
        nationality: "Greek, Hellenic",
    },
    {
        num_code: "304",
        alpha_2_code: "GL",
        alpha_3_code: "GRL",
        label: "Greenland",
        nationality: "Greenlandic",
    },
    {
        num_code: "308",
        alpha_2_code: "GD",
        alpha_3_code: "GRD",
        label: "Grenada",
        nationality: "Grenadian",
    },
    {
        num_code: "312",
        alpha_2_code: "GP",
        alpha_3_code: "GLP",
        label: "Guadeloupe",
        nationality: "Guadeloupe",
    },
    {
        num_code: "316",
        alpha_2_code: "GU",
        alpha_3_code: "GUM",
        label: "Guam",
        nationality: "Guamanian, Guambat",
    },
    {
        num_code: "320",
        alpha_2_code: "GT",
        alpha_3_code: "GTM",
        label: "Guatemala",
        nationality: "Guatemalan",
    },
    {
        num_code: "831",
        alpha_2_code: "GG",
        alpha_3_code: "GGY",
        label: "Guernsey",
        nationality: "Channel Island",
    },
    {
        num_code: "324",
        alpha_2_code: "GN",
        alpha_3_code: "GIN",
        label: "Guinea",
        nationality: "Guinean",
    },
    {
        num_code: "624",
        alpha_2_code: "GW",
        alpha_3_code: "GNB",
        label: "Guinea-Bissau",
        nationality: "Bissau-Guinean",
    },
    {
        num_code: "328",
        alpha_2_code: "GY",
        alpha_3_code: "GUY",
        label: "Guyana",
        nationality: "Guyanese",
    },
    {
        num_code: "332",
        alpha_2_code: "HT",
        alpha_3_code: "HTI",
        label: "Haiti",
        nationality: "Haitian",
    },
    {
        num_code: "334",
        alpha_2_code: "HM",
        alpha_3_code: "HMD",
        label: "Heard Island and McDonald Islands",
        nationality: "Heard Island or McDonald Islands",
    },
    {
        num_code: "336",
        alpha_2_code: "VA",
        alpha_3_code: "VAT",
        label: "Vatican City State",
        nationality: "Vatican",
    },
    {
        num_code: "340",
        alpha_2_code: "HN",
        alpha_3_code: "HND",
        label: "Honduras",
        nationality: "Honduran",
    },
    {
        num_code: "344",
        alpha_2_code: "HK",
        alpha_3_code: "HKG",
        label: "Hong Kong",
        nationality: "Hong Kong, Hong Kongese",
    },
    {
        num_code: "348",
        alpha_2_code: "HU",
        alpha_3_code: "HUN",
        label: "Hungary",
        nationality: "Hungarian, Magyar",
    },
    {
        num_code: "352",
        alpha_2_code: "IS",
        alpha_3_code: "ISL",
        label: "Iceland",
        nationality: "Icelandic",
    },
    {
        num_code: "356",
        alpha_2_code: "IN",
        alpha_3_code: "IND",
        label: "India",
        nationality: "Indian",
    },
    {
        num_code: "360",
        alpha_2_code: "ID",
        alpha_3_code: "IDN",
        label: "Indonesia",
        nationality: "Indonesian",
    },
    {
        num_code: "364",
        alpha_2_code: "IR",
        alpha_3_code: "IRN",
        label: "Iran",
        nationality: "Iranian, Persian",
    },
    {
        num_code: "368",
        alpha_2_code: "IQ",
        alpha_3_code: "IRQ",
        label: "Iraq",
        nationality: "Iraqi",
    },
    {
        num_code: "372",
        alpha_2_code: "IE",
        alpha_3_code: "IRL",
        label: "Ireland",
        nationality: "Irish",
    },
    {
        num_code: "833",
        alpha_2_code: "IM",
        alpha_3_code: "IMN",
        label: "Isle of Man",
        nationality: "Manx",
    },
    {
        num_code: "376",
        alpha_2_code: "IL",
        alpha_3_code: "ISR",
        label: "Israel",
        nationality: "Israeli",
    },
    {
        num_code: "380",
        alpha_2_code: "IT",
        alpha_3_code: "ITA",
        label: "Italy",
        nationality: "Italian",
    },
    {
        num_code: "388",
        alpha_2_code: "JM",
        alpha_3_code: "JAM",
        label: "Jamaica",
        nationality: "Jamaican",
    },
    {
        num_code: "392",
        alpha_2_code: "JP",
        alpha_3_code: "JPN",
        label: "Japan",
        nationality: "Japanese",
    },
    {
        num_code: "832",
        alpha_2_code: "JE",
        alpha_3_code: "JEY",
        label: "Jersey",
        nationality: "Channel Island",
    },
    {
        num_code: "400",
        alpha_2_code: "JO",
        alpha_3_code: "JOR",
        label: "Jordan",
        nationality: "Jordanian",
    },
    {
        num_code: "398",
        alpha_2_code: "KZ",
        alpha_3_code: "KAZ",
        label: "Kazakhstan",
        nationality: "Kazakhstani, Kazakh",
    },
    {
        num_code: "404",
        alpha_2_code: "KE",
        alpha_3_code: "KEN",
        label: "Kenya",
        nationality: "Kenyan",
    },
    {
        num_code: "296",
        alpha_2_code: "KI",
        alpha_3_code: "KIR",
        label: "Kiribati",
        nationality: "I-Kiribati",
    },
    {
        num_code: "408",
        alpha_2_code: "KP",
        alpha_3_code: "PRK",
        label: "Korea (Democratic People's Republic of)",
        nationality: "North Korean",
    },
    {
        num_code: "410",
        alpha_2_code: "KR",
        alpha_3_code: "KOR",
        label: "Korea (Republic of)",
        nationality: "South Korean",
    },
    {
        num_code: "414",
        alpha_2_code: "KW",
        alpha_3_code: "KWT",
        label: "Kuwait",
        nationality: "Kuwaiti",
    },
    {
        num_code: "417",
        alpha_2_code: "KG",
        alpha_3_code: "KGZ",
        label: "Kyrgyzstan",
        nationality: "Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz",
    },
    {
        num_code: "418",
        alpha_2_code: "LA",
        alpha_3_code: "LAO",
        label: "Lao People's Democratic Republic",
        nationality: "Lao, Laotian",
    },
    {
        num_code: "428",
        alpha_2_code: "LV",
        alpha_3_code: "LVA",
        label: "Latvia",
        nationality: "Latvian",
    },
    {
        num_code: "422",
        alpha_2_code: "LB",
        alpha_3_code: "LBN",
        label: "Lebanon",
        nationality: "Lebanese",
    },
    {
        num_code: "426",
        alpha_2_code: "LS",
        alpha_3_code: "LSO",
        label: "Lesotho",
        nationality: "Basotho",
    },
    {
        num_code: "430",
        alpha_2_code: "LR",
        alpha_3_code: "LBR",
        label: "Liberia",
        nationality: "Liberian",
    },
    {
        num_code: "434",
        alpha_2_code: "LY",
        alpha_3_code: "LBY",
        label: "Libya",
        nationality: "Libyan",
    },
    {
        num_code: "438",
        alpha_2_code: "LI",
        alpha_3_code: "LIE",
        label: "Liechtenstein",
        nationality: "Liechtenstein",
    },
    {
        num_code: "440",
        alpha_2_code: "LT",
        alpha_3_code: "LTU",
        label: "Lithuania",
        nationality: "Lithuanian",
    },
    {
        num_code: "442",
        alpha_2_code: "LU",
        alpha_3_code: "LUX",
        label: "Luxembourg",
        nationality: "Luxembourg, Luxembourgish",
    },
    {
        num_code: "446",
        alpha_2_code: "MO",
        alpha_3_code: "MAC",
        label: "Macao",
        nationality: "Macanese, Chinese",
    },
    {
        num_code: "807",
        alpha_2_code: "MK",
        alpha_3_code: "MKD",
        label: "Macedonia (the former Yugoslav Republic of)",
        nationality: "Macedonian",
    },
    {
        num_code: "450",
        alpha_2_code: "MG",
        alpha_3_code: "MDG",
        label: "Madagascar",
        nationality: "Malagasy",
    },
    {
        num_code: "454",
        alpha_2_code: "MW",
        alpha_3_code: "MWI",
        label: "Malawi",
        nationality: "Malawian",
    },
    {
        num_code: "458",
        alpha_2_code: "MY",
        alpha_3_code: "MYS",
        label: "Malaysia",
        nationality: "Malaysian",
    },
    {
        num_code: "462",
        alpha_2_code: "MV",
        alpha_3_code: "MDV",
        label: "Maldives",
        nationality: "Maldivian",
    },
    {
        num_code: "466",
        alpha_2_code: "ML",
        alpha_3_code: "MLI",
        label: "Mali",
        nationality: "Malian, Malinese",
    },
    {
        num_code: "470",
        alpha_2_code: "MT",
        alpha_3_code: "MLT",
        label: "Malta",
        nationality: "Maltese",
    },
    {
        num_code: "584",
        alpha_2_code: "MH",
        alpha_3_code: "MHL",
        label: "Marshall Islands",
        nationality: "Marshallese",
    },
    {
        num_code: "474",
        alpha_2_code: "MQ",
        alpha_3_code: "MTQ",
        label: "Martinique",
        nationality: "Martiniquais, Martinican",
    },
    {
        num_code: "478",
        alpha_2_code: "MR",
        alpha_3_code: "MRT",
        label: "Mauritania",
        nationality: "Mauritanian",
    },
    {
        num_code: "480",
        alpha_2_code: "MU",
        alpha_3_code: "MUS",
        label: "Mauritius",
        nationality: "Mauritian",
    },
    {
        num_code: "175",
        alpha_2_code: "YT",
        alpha_3_code: "MYT",
        label: "Mayotte",
        nationality: "Mahoran",
    },
    {
        num_code: "484",
        alpha_2_code: "MX",
        alpha_3_code: "MEX",
        label: "Mexico",
        nationality: "Mexican",
    },
    {
        num_code: "583",
        alpha_2_code: "FM",
        alpha_3_code: "FSM",
        label: "Micronesia (Federated States of)",
        nationality: "Micronesian",
    },
    {
        num_code: "498",
        alpha_2_code: "MD",
        alpha_3_code: "MDA",
        label: "Moldova (Republic of)",
        nationality: "Moldovan",
    },
    {
        num_code: "492",
        alpha_2_code: "MC",
        alpha_3_code: "MCO",
        label: "Monaco",
        nationality: "Mon\u00e9gasque, Monacan",
    },
    {
        num_code: "496",
        alpha_2_code: "MN",
        alpha_3_code: "MNG",
        label: "Mongolia",
        nationality: "Mongolian",
    },
    {
        num_code: "499",
        alpha_2_code: "ME",
        alpha_3_code: "MNE",
        label: "Montenegro",
        nationality: "Montenegrin",
    },
    {
        num_code: "500",
        alpha_2_code: "MS",
        alpha_3_code: "MSR",
        label: "Montserrat",
        nationality: "Montserratian",
    },
    {
        num_code: "504",
        alpha_2_code: "MA",
        alpha_3_code: "MAR",
        label: "Morocco",
        nationality: "Moroccan",
    },
    {
        num_code: "508",
        alpha_2_code: "MZ",
        alpha_3_code: "MOZ",
        label: "Mozambique",
        nationality: "Mozambican",
    },
    {
        num_code: "104",
        alpha_2_code: "MM",
        alpha_3_code: "MMR",
        label: "Myanmar",
        nationality: "Burmese",
    },
    {
        num_code: "516",
        alpha_2_code: "NA",
        alpha_3_code: "NAM",
        label: "Namibia",
        nationality: "Namibian",
    },
    {
        num_code: "520",
        alpha_2_code: "NR",
        alpha_3_code: "NRU",
        label: "Nauru",
        nationality: "Nauruan",
    },
    {
        num_code: "524",
        alpha_2_code: "NP",
        alpha_3_code: "NPL",
        label: "Nepal",
        nationality: "Nepali, Nepalese",
    },
    {
        num_code: "528",
        alpha_2_code: "NL",
        alpha_3_code: "NLD",
        label: "Netherlands",
        nationality: "Dutch, Netherlandic",
    },
    {
        num_code: "540",
        alpha_2_code: "NC",
        alpha_3_code: "NCL",
        label: "New Caledonia",
        nationality: "New Caledonian",
    },
    {
        num_code: "554",
        alpha_2_code: "NZ",
        alpha_3_code: "NZL",
        label: "New Zealand",
        nationality: "New Zealand, NZ",
    },
    {
        num_code: "558",
        alpha_2_code: "NI",
        alpha_3_code: "NIC",
        label: "Nicaragua",
        nationality: "Nicaraguan",
    },
    {
        num_code: "562",
        alpha_2_code: "NE",
        alpha_3_code: "NER",
        label: "Niger",
        nationality: "Nigerien",
    },
    {
        num_code: "566",
        alpha_2_code: "NG",
        alpha_3_code: "NGA",
        label: "Nigeria",
        nationality: "Nigerian",
    },
    {
        num_code: "570",
        alpha_2_code: "NU",
        alpha_3_code: "NIU",
        label: "Niue",
        nationality: "Niuean",
    },
    {
        num_code: "574",
        alpha_2_code: "NF",
        alpha_3_code: "NFK",
        label: "Norfolk Island",
        nationality: "Norfolk Island",
    },
    {
        num_code: "580",
        alpha_2_code: "MP",
        alpha_3_code: "MNP",
        label: "Northern Mariana Islands",
        nationality: "Northern Marianan",
    },
    {
        num_code: "578",
        alpha_2_code: "NO",
        alpha_3_code: "NOR",
        label: "Norway",
        nationality: "Norwegian",
    },
    {
        num_code: "512",
        alpha_2_code: "OM",
        alpha_3_code: "OMN",
        label: "Oman",
        nationality: "Omani",
    },
    {
        num_code: "586",
        alpha_2_code: "PK",
        alpha_3_code: "PAK",
        label: "Pakistan",
        nationality: "Pakistani",
    },
    {
        num_code: "585",
        alpha_2_code: "PW",
        alpha_3_code: "PLW",
        label: "Palau",
        nationality: "Palauan",
    },
    {
        num_code: "275",
        alpha_2_code: "PS",
        alpha_3_code: "PSE",
        label: "Palestine, State of",
        nationality: "Palestinian",
    },
    {
        num_code: "591",
        alpha_2_code: "PA",
        alpha_3_code: "PAN",
        label: "Panama",
        nationality: "Panamanian",
    },
    {
        num_code: "598",
        alpha_2_code: "PG",
        alpha_3_code: "PNG",
        label: "Papua New Guinea",
        nationality: "Papua New Guinean, Papuan",
    },
    {
        num_code: "600",
        alpha_2_code: "PY",
        alpha_3_code: "PRY",
        label: "Paraguay",
        nationality: "Paraguayan",
    },
    {
        num_code: "604",
        alpha_2_code: "PE",
        alpha_3_code: "PER",
        label: "Peru",
        nationality: "Peruvian",
    },
    {
        num_code: "608",
        alpha_2_code: "PH",
        alpha_3_code: "PHL",
        label: "Philippines",
        nationality: "Philippine, Filipino",
    },
    {
        num_code: "612",
        alpha_2_code: "PN",
        alpha_3_code: "PCN",
        label: "Pitcairn",
        nationality: "Pitcairn Island",
    },
    {
        num_code: "616",
        alpha_2_code: "PL",
        alpha_3_code: "POL",
        label: "Poland",
        nationality: "Polish",
    },
    {
        num_code: "620",
        alpha_2_code: "PT",
        alpha_3_code: "PRT",
        label: "Portugal",
        nationality: "Portuguese",
    },
    {
        num_code: "630",
        alpha_2_code: "PR",
        alpha_3_code: "PRI",
        label: "Puerto Rico",
        nationality: "Puerto Rican",
    },
    {
        num_code: "634",
        alpha_2_code: "QA",
        alpha_3_code: "QAT",
        label: "Qatar",
        nationality: "Qatari",
    },
    {
        num_code: "638",
        alpha_2_code: "RE",
        alpha_3_code: "REU",
        label: "R\u00e9union",
        nationality: "R\u00e9unionese, R\u00e9unionnais",
    },
    {
        num_code: "642",
        alpha_2_code: "RO",
        alpha_3_code: "ROU",
        label: "Romania",
        nationality: "Romanian",
    },
    {
        num_code: "643",
        alpha_2_code: "RU",
        alpha_3_code: "RUS",
        label: "Russian Federation",
        nationality: "Russian",
    },
    {
        num_code: "646",
        alpha_2_code: "RW",
        alpha_3_code: "RWA",
        label: "Rwanda",
        nationality: "Rwandan",
    },
    {
        num_code: "652",
        alpha_2_code: "BL",
        alpha_3_code: "BLM",
        label: "Saint Barth\u00e9lemy",
        nationality: "Barth\u00e9lemois",
    },
    {
        num_code: "654",
        alpha_2_code: "SH",
        alpha_3_code: "SHN",
        label: "Saint Helena, Ascension and Tristan da Cunha",
        nationality: "Saint Helenian",
    },
    {
        num_code: "659",
        alpha_2_code: "KN",
        alpha_3_code: "KNA",
        label: "Saint Kitts and Nevis",
        nationality: "Kittitian or Nevisian",
    },
    {
        num_code: "662",
        alpha_2_code: "LC",
        alpha_3_code: "LCA",
        label: "Saint Lucia",
        nationality: "Saint Lucian",
    },
    {
        num_code: "663",
        alpha_2_code: "MF",
        alpha_3_code: "MAF",
        label: "Saint Martin (French part)",
        nationality: "Saint-Martinoise",
    },
    {
        num_code: "666",
        alpha_2_code: "PM",
        alpha_3_code: "SPM",
        label: "Saint Pierre and Miquelon",
        nationality: "Saint-Pierrais or Miquelonnais",
    },
    {
        num_code: "670",
        alpha_2_code: "VC",
        alpha_3_code: "VCT",
        label: "Saint Vincent and the Grenadines",
        nationality: "Saint Vincentian, Vincentian",
    },
    {
        num_code: "882",
        alpha_2_code: "WS",
        alpha_3_code: "WSM",
        label: "Samoa",
        nationality: "Samoan",
    },
    {
        num_code: "674",
        alpha_2_code: "SM",
        alpha_3_code: "SMR",
        label: "San Marino",
        nationality: "Sammarinese",
    },
    {
        num_code: "678",
        alpha_2_code: "ST",
        alpha_3_code: "STP",
        label: "Sao Tome and Principe",
        nationality: "S\u00e3o Tom\u00e9an",
    },
    {
        num_code: "682",
        alpha_2_code: "SA",
        alpha_3_code: "SAU",
        label: "Saudi Arabia",
        nationality: "Saudi, Saudi Arabian",
    },
    {
        num_code: "686",
        alpha_2_code: "SN",
        alpha_3_code: "SEN",
        label: "Senegal",
        nationality: "Senegalese",
    },
    {
        num_code: "688",
        alpha_2_code: "RS",
        alpha_3_code: "SRB",
        label: "Serbia",
        nationality: "Serbian",
    },
    {
        num_code: "690",
        alpha_2_code: "SC",
        alpha_3_code: "SYC",
        label: "Seychelles",
        nationality: "Seychellois",
    },
    {
        num_code: "694",
        alpha_2_code: "SL",
        alpha_3_code: "SLE",
        label: "Sierra Leone",
        nationality: "Sierra Leonean",
    },
    {
        num_code: "702",
        alpha_2_code: "SG",
        alpha_3_code: "SGP",
        label: "Singapore",
        nationality: "Singaporean",
    },
    {
        num_code: "534",
        alpha_2_code: "SX",
        alpha_3_code: "SXM",
        label: "Sint Maarten (Dutch part)",
        nationality: "Sint Maarten",
    },
    {
        num_code: "703",
        alpha_2_code: "SK",
        alpha_3_code: "SVK",
        label: "Slovakia",
        nationality: "Slovak",
    },
    {
        num_code: "705",
        alpha_2_code: "SI",
        alpha_3_code: "SVN",
        label: "Slovenia",
        nationality: "Slovenian, Slovene",
    },
    {
        num_code: "90",
        alpha_2_code: "SB",
        alpha_3_code: "SLB",
        label: "Solomon Islands",
        nationality: "Solomon Island",
    },
    {
        num_code: "706",
        alpha_2_code: "SO",
        alpha_3_code: "SOM",
        label: "Somalia",
        nationality: "Somali, Somalian",
    },
    {
        num_code: "710",
        alpha_2_code: "ZA",
        alpha_3_code: "ZAF",
        label: "South Africa",
        nationality: "South African",
    },
    {
        num_code: "239",
        alpha_2_code: "GS",
        alpha_3_code: "SGS",
        label: "South Georgia and the South Sandwich Islands",
        nationality: "South Georgia or South Sandwich Islands",
    },
    {
        num_code: "728",
        alpha_2_code: "SS",
        alpha_3_code: "SSD",
        label: "South Sudan",
        nationality: "South Sudanese",
    },
    {
        num_code: "724",
        alpha_2_code: "ES",
        alpha_3_code: "ESP",
        label: "Spain",
        nationality: "Spanish",
    },
    {
        num_code: "144",
        alpha_2_code: "LK",
        alpha_3_code: "LKA",
        label: "Sri Lanka",
        nationality: "Sri Lankan",
    },
    {
        num_code: "729",
        alpha_2_code: "SD",
        alpha_3_code: "SDN",
        label: "Sudan",
        nationality: "Sudanese",
    },
    {
        num_code: "740",
        alpha_2_code: "SR",
        alpha_3_code: "SUR",
        label: "Suriname",
        nationality: "Surinamese",
    },
    {
        num_code: "744",
        alpha_2_code: "SJ",
        alpha_3_code: "SJM",
        label: "Svalbard and Jan Mayen",
        nationality: "Svalbard",
    },
    {
        num_code: "748",
        alpha_2_code: "SZ",
        alpha_3_code: "SWZ",
        label: "Swaziland",
        nationality: "Swazi",
    },
    {
        num_code: "752",
        alpha_2_code: "SE",
        alpha_3_code: "SWE",
        label: "Sweden",
        nationality: "Swedish",
    },
    {
        num_code: "756",
        alpha_2_code: "CH",
        alpha_3_code: "CHE",
        label: "Switzerland",
        nationality: "Swiss",
    },
    {
        num_code: "760",
        alpha_2_code: "SY",
        alpha_3_code: "SYR",
        label: "Syrian Arab Republic",
        nationality: "Syrian",
    },
    {
        num_code: "158",
        alpha_2_code: "TW",
        alpha_3_code: "TWN",
        label: "Taiwan, Province of China",
        nationality: "Chinese, Taiwanese",
    },
    {
        num_code: "762",
        alpha_2_code: "TJ",
        alpha_3_code: "TJK",
        label: "Tajikistan",
        nationality: "Tajikistani",
    },
    {
        num_code: "834",
        alpha_2_code: "TZ",
        alpha_3_code: "TZA",
        label: "Tanzania, United Republic of",
        nationality: "Tanzanian",
    },
    {
        num_code: "764",
        alpha_2_code: "TH",
        alpha_3_code: "THA",
        label: "Thailand",
        nationality: "Thai",
    },
    {
        num_code: "626",
        alpha_2_code: "TL",
        alpha_3_code: "TLS",
        label: "Timor-Leste",
        nationality: "Timorese",
    },
    {
        num_code: "768",
        alpha_2_code: "TG",
        alpha_3_code: "TGO",
        label: "Togo",
        nationality: "Togolese",
    },
    {
        num_code: "772",
        alpha_2_code: "TK",
        alpha_3_code: "TKL",
        label: "Tokelau",
        nationality: "Tokelauan",
    },
    {
        num_code: "776",
        alpha_2_code: "TO",
        alpha_3_code: "TON",
        label: "Tonga",
        nationality: "Tongan",
    },
    {
        num_code: "780",
        alpha_2_code: "TT",
        alpha_3_code: "TTO",
        label: "Trinidad and Tobago",
        nationality: "Trinidadian or Tobagonian",
    },
    {
        num_code: "788",
        alpha_2_code: "TN",
        alpha_3_code: "TUN",
        label: "Tunisia",
        nationality: "Tunisian",
    },
    {
        num_code: "792",
        alpha_2_code: "TR",
        alpha_3_code: "TUR",
        label: "Turkey",
        nationality: "Turkish",
    },
    {
        num_code: "795",
        alpha_2_code: "TM",
        alpha_3_code: "TKM",
        label: "Turkmenistan",
        nationality: "Turkmen",
    },
    {
        num_code: "796",
        alpha_2_code: "TC",
        alpha_3_code: "TCA",
        label: "Turks and Caicos Islands",
        nationality: "Turks and Caicos Island",
    },
    {
        num_code: "798",
        alpha_2_code: "TV",
        alpha_3_code: "TUV",
        label: "Tuvalu",
        nationality: "Tuvaluan",
    },
    {
        num_code: "800",
        alpha_2_code: "UG",
        alpha_3_code: "UGA",
        label: "Uganda",
        nationality: "Ugandan",
    },
    {
        num_code: "804",
        alpha_2_code: "UA",
        alpha_3_code: "UKR",
        label: "Ukraine",
        nationality: "Ukrainian",
    },
    {
        num_code: "784",
        alpha_2_code: "AE",
        alpha_3_code: "ARE",
        label: "United Arab Emirates",
        nationality: "Emirati, Emirian, Emiri",
    },
    {
        num_code: "826",
        alpha_2_code: "GB",
        alpha_3_code: "GBR",
        label: "United Kingdom of Great Britain and Northern Ireland",
        nationality: "British, UK",
    },
    {
        num_code: "581",
        alpha_2_code: "UM",
        alpha_3_code: "UMI",
        label: "United States Minor Outlying Islands",
        nationality: "American",
    },
    {
        num_code: "840",
        alpha_2_code: "US",
        alpha_3_code: "USA",
        label: "United States of America",
        nationality: "American",
    },
    {
        num_code: "858",
        alpha_2_code: "UY",
        alpha_3_code: "URY",
        label: "Uruguay",
        nationality: "Uruguayan",
    },
    {
        num_code: "860",
        alpha_2_code: "UZ",
        alpha_3_code: "UZB",
        label: "Uzbekistan",
        nationality: "Uzbekistani, Uzbek",
    },
    {
        num_code: "548",
        alpha_2_code: "VU",
        alpha_3_code: "VUT",
        label: "Vanuatu",
        nationality: "Ni-Vanuatu, Vanuatuan",
    },
    {
        num_code: "862",
        alpha_2_code: "VE",
        alpha_3_code: "VEN",
        label: "Venezuela (Bolivarian Republic of)",
        nationality: "Venezuelan",
    },
    {
        num_code: "704",
        alpha_2_code: "VN",
        alpha_3_code: "VNM",
        label: "Vietnam",
        nationality: "Vietnamese",
    },
    {
        num_code: "92",
        alpha_2_code: "VG",
        alpha_3_code: "VGB",
        label: "Virgin Islands (British)",
        nationality: "British Virgin Island",
    },
    {
        num_code: "850",
        alpha_2_code: "VI",
        alpha_3_code: "VIR",
        label: "Virgin Islands (U.S.)",
        nationality: "U.S. Virgin Island",
    },
    {
        num_code: "876",
        alpha_2_code: "WF",
        alpha_3_code: "WLF",
        label: "Wallis and Futuna",
        nationality: "Wallis and Futuna, Wallisian or Futunan",
    },
    {
        num_code: "732",
        alpha_2_code: "EH",
        alpha_3_code: "ESH",
        label: "Western Sahara",
        nationality: "Sahrawi, Sahrawian, Sahraouian",
    },
    {
        num_code: "887",
        alpha_2_code: "YE",
        alpha_3_code: "YEM",
        label: "Yemen",
        nationality: "Yemeni",
    },
    {
        num_code: "894",
        alpha_2_code: "ZM",
        alpha_3_code: "ZMB",
        label: "Zambia",
        nationality: "Zambian",
    },
    {
        num_code: "716",
        alpha_2_code: "ZW",
        alpha_3_code: "ZWE",
        label: "Zimbabwe",
        nationality: "Zimbabwean",
    },
]
export default Countries;