# Generated by Django 3.0 on 2022-01-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220119_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emil_otp',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
